let a = 5;
let b = 3;
let sum = a + b;
let difference = a - b;
let product = a * b;
let quotient = a / b;
let remainder = a % b;
console.log(sum);
console.log(difference);
console.log(product);
console.log(quotient);
console.log(remainder);
